Makefile.performer:
	@:

build:
	@musical-patterns-cli build "webpack --config webpack.prod.js"

build-dev:
	@webpack --config webpack.dev.js

start:
	@webpack-dev-server --config webpack.qa.js --color
